VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cDrives"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'***********************************************************************************
'Return all Drives installed on the Users Local System using the FileSystemObject and
'add to frmExplorer.Explorer(TreeView).
'***********************************************************************************

Option Explicit



'***********************************************************************************
'Return all Drives installed on the Users Local System using the FileSystemObject
'***********************************************************************************


